name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.16
    
    - name: Install migration lib
      run: go get -v github.com/rubenv/sql-migrate/...
    
    - name: config pg container
      run: make postgres

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
#tag with para prover input parametros para uma action
#options com opções que retornam avisos de status de build do postgres