name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
#tag with para prover input parametros para uma action